trigger:
  - master
pr:
  branches:
    exclude:
    - "*"

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'DX12 x64'
  buildConfiguration: 'Release'

steps:
- script: git submodule update --init --recursive
  displayName: 'Fetch git submodules'

- script: .\premake\premake5.exe vs2019
  displayName: 'Run premake'

- task: VSBuild@1
  inputs:
    solution: 'Sail.sln'
    vsVersion: '16.0'
    platform: 'DX12 x64'
    configuration: 'Release'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './bin/DX12 x64-Release/Demo/Demo.exe'
    ArtifactName: 'drop'
    publishLocation: 'Container'
