#pragma once

#include "Component.h"

#include "AiComponent.h"
#include "AnimationComponent.h"
#include "AudioComponent.h"
#include "BoundingBoxComponent.h"
#include "CandleComponent.h"
#include "CollidableComponent.h"
#include "CollisionComponent.h"
#include "CollisionSpheresComponent.h"
#include "CullingComponent.h"
#include "FSMComponent.h"
#include "GunComponent.h"
#include "LifeTimeComponent.h"
#include "LightComponent.h"
#include "SpotlightComponent.h"
#include "LightListComponent.h"
#include "LocalOwnerComponent.h"
#include "MapComponent.h"
#include "MetaballComponent.h"
#include "ModelComponent.h"
#include "MovementComponent.h"
#include "NetworkReceiverComponent.h"
#include "NetworkSenderComponent.h"
#include "OnlineOwnerComponent.h"
#include "ParticleEmitterComponent.h"
#include "ProjectileComponent.h"
#include "RealTimeComponent.h"
#include "SpectatorComponent.h"
#include "SpeedLimitComponent.h"
//#include "TextComponent.h"
#include "TransformComponent.h"
#include "VerticalCylinderComponent.h"
#include "SprintingComponent.h"

#include "GUIComponent.h"