#include "pch.h"
//#include "MaterialComponent.h"
//
//#include "Sail/api/gui/SailGuiWindow.h"
//#include "imgui.h"
//#include "glm/gtc/type_ptr.hpp"
//#include "Sail/api/Texture.h"
//#include "Sail/graphics/geometry/Model.h"
//#include "Sail/utils/Utils.h"
//#include "Sail/graphics/material/PhongMaterial.h"
//#include "Sail/graphics/material/PBRMaterial.h"
//#include "Sail/graphics/material/TexturesMaterial.h"
//#include "imgui_internal.h"