#include "pch.h"
#include "NetworkSenderComponent.h"

NetworkSenderComponent::NetworkSenderComponent(Netcode::NetworkDataType dataType, Netcode::NetworkEntityType entityType, unsigned char ownerID) :
	// Set the first byte of the object ID as the ownerID and the rest as the unique ID generated by the player
	m_id(Netcode::createNetworkID() | (static_cast<Netcode::NetworkObjectID>(ownerID) << 18)), 
	m_dataType(dataType), m_entityType(entityType)
{}

NetworkSenderComponent::~NetworkSenderComponent() 
{}

