#include "pch.h"
#include "NetworkSenderComponent.h"

NetworSenderComponent::NetworSenderComponent(Netcode::NetworkDataType type, unsigned char ownerID) {
	// Set the first byte of the object ID as the ownerID and the rest as the unique ID generated by the player
	data.objectID = Netcode::createNetworkID() | (static_cast<Netcode::NetworkObjectID>(ownerID) << 18);
	data.type = type;
}

NetworSenderComponent::~NetworSenderComponent() {

}

