#pragma once
#include "KeyCodes.h"

#define SAIL_KEYBIND_ALT						SAIL_KEY_MENU
#define SAIL_KEYBIND_F4							SAIL_KEY_F4
#define SAIL_KEYBIND_ADD_LIGHT					SAIL_KEY_E
#define SAIL_KEYBIND_SHOW_BOUNDING_BOXES		SAIL_KEY_1
#define SAIL_KEYBIND_HIDE_BOUNDING_BOXES		SAIL_KEY_2
#define SAIL_KEYBIND_TEST_RAY_INTERSECTION		SAIL_KEY_O
#define SAIL_KEYBIND_TOGGLE_AI_FOLLOWING_PLAYER	SAIL_KEY_H
#define SAIL_KEYBIND_SET_DIRECTIONAL_LIGHT		SAIL_KEY_G
#define SAIL_KEYBIND_TOGGLE_CONSOLE				SAIL_KEY_OEM_5
#define SAIL_KEYBIND_RELOAD_SHADERS				SAIL_KEY_R
											//	SAIL_KEY_Z
											//	SAIL_KEY_V
#define SAIL_KEYBIND_REMOVE_OLDEST_LIGHT		SAIL_KEY_X
#define SAIL_KEYBIND_SPRINT						SAIL_KEY_SHIFT
#define SAIL_KEYBIND_MOVE_FORWARD				SAIL_KEY_W
#define SAIL_KEYBIND_MOVE_BACKWARD				SAIL_KEY_S
#define SAIL_KEYBIND_MOVE_RIGHT					SAIL_KEY_D
#define SAIL_KEYBIND_MOVE_LEFT					SAIL_KEY_A
#define SAIL_KEYBIND_JUMP						SAIL_KEY_SPACE
//#define SAIL_KEYBIND
//#define SAIL_KEYBIND
//#define SAIL_KEYBIND
//#define SAIL_KEYBIND
//#define SAIL_KEYBIND