#pragma once

#define SAIL_MOUSE_BUTTON_1      0
#define SAIL_MOUSE_BUTTON_2      1
#define SAIL_MOUSE_BUTTON_3      2
#define SAIL_MOUSE_BUTTON_4      3
#define SAIL_MOUSE_BUTTON_5      4
//#define SAIL_MOUSE_WHEEL         5
//#define SAIL_MOUSE_HWHEEL        6
#define SAIL_MOUSE_LEFT_BUTTON   SAIL_MOUSE_BUTTON_1
#define SAIL_MOUSE_RIGHT_BUTTON  SAIL_MOUSE_BUTTON_2
#define SAIL_MOUSE_MIDDLE_BUTTON SAIL_MOUSE_BUTTON_3

#define SAIL_NUM_MOUSE_BUTTONS 5