#pragma once
#include "EventDispatcher.h"

// Ordered by name

#include "types/ChangeWalkingSoundEvent.h"
#include "types/HoldingCandleToggleEvent.h"
#include "types/IgniteCandleEvent.h"
#include "types/LoopShootingEvent.h"
#include "types/NewFrameEvent.h"
#include "types/PlayerDiedEvent.h"
#include "types/PlayerJumpedEvent.h"
#include "types/PlayerLandedEvent.h"
#include "types/StartShootingEvent.h"
#include "types/StartThrowingEvent.h"
#include "types/StopShootingEvent.h"
#include "types/StopThrowingEvent.h"
#include "types/StopWalkingEvent.h"
#include "types/StartKillCamEvent.h"
#include "types/StopKillCamEvent.h"
#include "types/ToggleSlowMotionReplayEvent.h"
#include "types/TorchExtinguishedEvent.h"
#include "types/TorchNotHeldEvent.h"
#include "types/UpdateSanityEvent.h"
#include "types/WaterHitPlayerEvent.h"
#include "types/WindowFocusChangedEvent.h"
#include "types/WindowResizeEvent.h"
#include "types/SpawnPowerUp.h"
